# Generated by Django 4.0.5 on 2022-06-10 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_description', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('IsActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('City', 'City'), ('Country', 'Country'), ('State', 'State')], max_length=50)),
                ('full_name', models.CharField(default='Jasola Vihar New Delhi', max_length=255, unique=True)),
                ('postal_code', models.CharField(max_length=6)),
                ('IsActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_description', models.CharField(max_length=500, unique=True)),
                ('url', models.URLField(default='https://example.com')),
                ('logo_url', models.URLField(default='https://example.com/abc.jpg')),
                ('fb_url', models.URLField(default='https://facebook.com')),
                ('insta_url', models.URLField(default='https://instagram.com')),
                ('linkedin_url', models.URLField(default='https://linkedin.com')),
                ('twitter_url', models.URLField(default='https://twitter.com')),
                ('contact_type', models.CharField(choices=[('Admission', 'Admission'), ('Support', 'Support')], max_length=50)),
                ('contact_number', models.CharField(default='+91 962 883 3068', max_length=16)),
                ('location_country', models.CharField(max_length=100)),
                ('IsActive', models.BooleanField(default=True)),
                ('location', models.ManyToManyField(blank=True, to='Site.location')),
            ],
        ),
        migrations.CreateModel(
            name='ProvidersCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=16)),
                ('average_cost_to_stay', models.CharField(max_length=20)),
                ('average_cost_to_stay_currency', models.CharField(choices=[('USD', 'USD'), ('INR', 'INR')], max_length=5)),
                ('recognitions', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('FullTime', 'Full Time'), ('PartTime', 'Part Time')], max_length=100)),
                ('mode', models.CharField(choices=[('Distance', 'Distance'), ('Regular', 'Regular')], max_length=100)),
                ('fee', models.CharField(max_length=20)),
                ('fee_currency', models.CharField(choices=[('USD', 'USD'), ('INR', 'INR')], max_length=5)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('meta_keywords', models.CharField(max_length=255)),
                ('meta_description', models.CharField(max_length=255)),
                ('IsActive', models.BooleanField(default=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.course')),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.provider')),
            ],
        ),
    ]
