# Generated by Django 4.0.5 on 2022-06-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='My Business Name', max_length=255)),
                ('mobile', models.CharField(default='+91 962 883 3068', max_length=16)),
                ('mobile2', models.CharField(default='', max_length=16)),
                ('mobile3', models.CharField(default='', max_length=16)),
                ('whatsapp', models.CharField(default='', max_length=16)),
                ('tollfree', models.CharField(default='18008890382', max_length=16)),
                ('email', models.EmailField(default='support@example.com', max_length=254)),
                ('logo_url', models.URLField(default='https://example.com/abc.jpg')),
                ('favicon_url', models.URLField(default='https://example.com/abc.jpg')),
                ('fb_url', models.URLField(default='https://facebook.com')),
                ('insta_url', models.URLField(default='https://instagram.com')),
                ('linkedin_url', models.URLField(default='https://linkedin.com')),
                ('twitter_url', models.URLField(default='https://twitter.com')),
                ('youtube_url', models.URLField(default='https://youtube.com')),
                ('meta_title', models.CharField(default='Meta Title', max_length=255)),
                ('meta_keywords', models.CharField(default='Meta Keywords', max_length=500)),
                ('meta_description', models.CharField(default='Meta Description', max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='providerscourse',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='providerscourse',
            old_name='provider_id',
            new_name='provider',
        ),
    ]
