# Generated by Django 4.0.5 on 2022-06-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_sitesetting_rename_course_id_providerscourse_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='mobile2',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='mobile3',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='whatsapp',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
