# Generated by Django 4.0.5 on 2022-06-10 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_alter_sitesetting_mobile2_alter_sitesetting_mobile3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='location',
        ),
        migrations.AddField(
            model_name='provider',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.location'),
        ),
    ]
