# Generated by Django 4.0.5 on 2022-06-12 09:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0005_remove_provider_location_provider_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerscourse',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
