# Generated by Django 4.0.5 on 2022-06-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0007_sitesetting_business_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='banner1_description',
            field=models.CharField(default='Banner1 Description', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='banner1_title',
            field=models.CharField(default='Banner1 Title', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='banner2_description',
            field=models.CharField(default='Banner2 Description', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='banner2_title',
            field=models.CharField(default='Banner2 Title', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='banner_description',
            field=models.CharField(default='Banner Description', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='banner_title',
            field=models.CharField(default='Banner Title', max_length=255),
        ),
    ]
