# Generated by Django 4.0.5 on 2022-06-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0008_sitesetting_banner1_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='business_address',
            field=models.CharField(default='Business Address', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='business_city',
            field=models.CharField(default='Business City', max_length=75),
        ),
    ]
