# Generated by Django 4.0.5 on 2022-06-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0009_sitesetting_business_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='business_address',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='business_city',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='business_HO_address',
            field=models.CharField(default='Business HO Address', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='business_HO_city',
            field=models.CharField(default='Business HO City', max_length=75),
        ),
    ]
