# Generated by Django 4.0.5 on 2022-06-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0010_remove_sitesetting_business_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='meta_author',
            field=models.CharField(default='Meta Author', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='meta_website',
            field=models.CharField(default='Meta Website', max_length=255),
        ),
    ]
