# Generated by Django 4.0.5 on 2022-06-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0011_sitesetting_meta_author_sitesetting_meta_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='ga_code',
            field=models.CharField(default='NA', help_text='google analytics code', max_length=16),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='go_code',
            field=models.CharField(default='NA', help_text='google optimizer code', max_length=16),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='gtm_code',
            field=models.CharField(default='NA', help_text='google tag manager code', max_length=16),
        ),
    ]
