# Generated by Django 4.0.5 on 2022-06-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0017_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='photo_path',
            field=models.ImageField(blank=True, null=True, upload_to='FeedBacks/photo'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_path',
            field=models.ImageField(blank=True, help_text='for in-writing image/photo', null=True, upload_to='FeedBacks/doc_img'),
        ),
    ]
