# Generated by Django 4.0.5 on 2022-06-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0018_feedback_photo_path_alter_feedback_feedback_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
