# Generated by Django 4.0.5 on 2022-06-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0020_sitesetting_meta_robots'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.SlugField(blank=True, max_length=450, null=True),
        ),
    ]
