# Generated by Django 4.0.5 on 2022-06-16 20:38

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0021_location_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
