# Generated by Django 4.0.5 on 2022-06-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0022_location_description_location_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='meta_description',
            field=models.CharField(blank=True, default=' ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='meta_keywords',
            field=models.CharField(blank=True, default=' ', max_length=255, null=True),
        ),
    ]
