# Generated by Django 4.0.5 on 2022-06-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0024_alter_location_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackrequest',
            name='comment',
            field=models.CharField(blank=True, default='NA', max_length=850, null=True),
        ),
    ]
