# Generated by Django 4.0.5 on 2022-06-20 15:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0026_delete_callbackrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='short_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
