# Generated by Django 4.0.5 on 2022-07-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0027_alter_provider_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='fb_page_id',
            field=models.CharField(default='NA', help_text='PageId : FB Messanger Chat Plugin', max_length=16),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='featured_video_url',
            field=models.URLField(default='https://youtube.com'),
        ),
    ]
