# Generated by Django 4.0.5 on 2022-07-07 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Site', '0029_provider_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='fb_admin_id',
            field=models.CharField(default='NaN', help_text='fb:admins : Facebook Admin ID - go to page viewsource search User_ID, if you are admin', max_length=255),
        ),
    ]
