# Generated by Django 4.0.5 on 2022-07-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0032_provider_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='logo_url_dark',
            field=models.URLField(default='https://example.com/abc.jpg'),
        ),
    ]
