# Generated by Django 3.2.9 on 2023-05-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0034_auto_20230508_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='hubspot_track_code',
            field=models.CharField(default='NA', help_text='Hubspot Tracking code : Marketting form from HubSpot CMS', max_length=16),
        ),
    ]
