# Generated by Django 3.2.9 on 2023-05-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackrequest',
            name='callback_url',
            field=models.URLField(default='https://admissionsquare.in?q=test', max_length=900),
        ),
    ]
